#cloud-config
package_upgrade: true
packages:
  - nginx
write_files:
- content: |
    <html>Welcome to fwpoctimw.uksouth.cloudapp.azure.com</html>
  path: /var/www/fwpoctimw.uksouth.cloudapp.azure.com/index.html
  owner: root:root
- path: /etc/letsencrypt/live/fwpoctimw.uksouth.cloudapp.azure.com/privkey.pem
  owner: root:root
  content: |
    -----BEGIN PRIVATE KEY-----
    MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQDHKFsUvjkprI4z
    B9/sAYxWWbqEbY0buGoFS/hpBbFZbquFLOLkLiE1/JqKuTdeNnBOAetmxliUdUaB
    cm2qppZpF6aZOCk7bYVAvUlQUDBtQSPPumdJ/Gi3v/fn/hq1HtYk65h45aAKxqzw
    a1J5VwT/w2xXnSkJZPRwJJt5xVL1XSfJZl1LHa8cQtGt782tk0eUJzA/KkoP+7Dr
    BC5npCQJeyyvO9IXXZ5oTv1dxa0hhHfQwJUrfdQ2IPZSnpMYfx8Fl4FgP2LuEKx4
    tLeCwgDjRl3SXIXT62MOpi63galME9qVfnY2uxYyaMwvLN6wTSCtByAXahwra8ar
    IMsnZY/JAgMBAAECggEAU37j0Kp/pK0nYNWoV3W+tGUiAWs8gaarLFVRbBZq6Cex
    2T+cUDXWzp982zQTtnf0VYAQhSIa+QLB8Htc5vK4lI7J1erpvnSILUAugHFeHC/3
    J5vqueYMsRzWfnjWEaE//nKXlfgPRPVOg+06woxtGB2CSqklDz84C9wNItxLj3ol
    Y0sdK8qKP58eFrweV4OIOJ28iFtd4PHKfTRxW1a4PmCV53BOoIf/wk0fcXmmNmoA
    IkmzKiATSHnHpIXJG1B84aNxLJ3JTDFW/nmIg/r+u7vDw10W77Hlqfiz/+QB/n/4
    H7N2+3nS8ORv2qOmx4oNWEvIvgZ77lWDfA9glshpQQKBgQDiBR1FJJmSjTlIZkmq
    PlPBrJlcGl6hyn7irK6LSNtVw8s/yANVJyAQef1QJBq4KvFVkbzXTZmxsk4Q5RNm
    romaM4bu0PMPeMPaYgSHEydL97LSctvc/HriXhYFJmekugPstOuq3RJwKSPOTRNA
    BDQ33nYCUcChXbDB+J+NHoZIHQKBgQDhkxX+jpLQUt9eg+RnmlBCXzTIWOX8T1Rf
    ybFejCr51E65u5hvqbQHjh6tM3iSf4kyTm1GDIWIg8bR6jHcr3zqNZtfdqxQFeeI
    CX15xFu7+dO55ItoqD/RHf/zX09xohtYp9qfrlOBAL2fybGNRnURLztZ1SxQAuZY
    We1j/dTOnQKBgBtrwWxVD2ivR4bYGhHUc/boSMba0CZS2egISTjOwwV5tpvrWTQo
    hgRZuHjTmIZFd3gJMV7xpDbhygTUtfDcNgeGPtWUdhinbyN8hs4YbckSqRhNJQ1/
    eC0kewlu6l4az0UVgg39ujHvW8+4nCBFIkyw6aJIZtVs93fhAQJu9J2lAn8oiEVr
    eDLpO/rnAMwJ0bCaPIE/frnUnGyMybEVTBpsyblbplm9tsCimuboOFdx+3irkWwR
    Ki7UWNlg3rQW83F+pCNHBAvyV/1CdHIXbzEMldd1j5t9Mr5E1R8om/eqc3Z2d7LQ
    /oICrB9mltdQi1h9vf7sJWHQ/rRlK8N8NCAJAoGBAKRuBsBu/4MxE2eaA2rRDvGr
    gc0pHMzZnfG45OgCEB3MvkjWPdBOXkGWr8q5/lw6jomzQKIhFDRtK2XQFaG+NXHg
    f/V9TTV+UvHONICboeDfTiarLg90b9bOCRbnM9m9XnUoEUdo6h63DX3oSoQmA4fx
    x6WH0ChK9Z1/znOGJnxh
    -----END PRIVATE KEY-----
- path: /etc/letsencrypt/ssl-dhparams.pem
  owner: root:root
  content: |
    -----BEGIN DH PARAMETERS-----
    MIIBCAKCAQEA//////////+t+FRYortKmq/cViAnPTzx2LnFg84tNpWp4TZBFGQz
    +8yTnc4kmz75fS/jY2MMddj2gbICrsRhetPfHtXV/WVhJDP1H18GbtCFY2VVPe0a
    87VXE15/V8k1mE8McODmi3fipona8+/och3xWKE2rec1MKzKT0g6eXq8CrGCsyT7
    YdEIqUuyyOP7uWrat2DX9GgdT0Kj3jlN9K5W7edjcrsZCwenyO4KbXCeAvzhzffi
    7MA0BM0oNC9hkXL+nOmFg/+OTxIy7vKBg8P+OxtMb61zO7X8vC7CIAXFjvGDfRaD
    ssbzSibBsu/6iGtCOGEoXJf//////////wIBAg==
    -----END DH PARAMETERS-----
- path: /etc/letsencrypt/options-ssl-nginx.conf
  owner: root:root
  content: |
    # This file contains important security parameters. If you modify this file
    # manually, Certbot will be unable to automatically provide future security
    # updates. Instead, Certbot will print and log an error message with a path to
    # the up-to-date file that you will need to refer to when manually updating
    # this file.

    ssl_session_cache shared:le_nginx_SSL:10m;
    ssl_session_timeout 1440m;
    ssl_session_tickets off;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
- path: /etc/letsencrypt/live/fwpoctimw.uksouth.cloudapp.azure.com/fullchain.pem
  owner: root:root
  content: |
    -----BEGIN CERTIFICATE-----
    MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
    WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
    RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
    R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
    sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
    NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
    Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
    /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
    AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
    Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
    FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
    AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
    Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
    gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
    PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
    ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
    CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
    lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
    avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
    yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
    yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
    hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
    HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
    MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
    nLRbwHOoq7hHwg==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
    MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
    DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
    ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
    wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
    LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
    4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
    bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
    sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
    Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
    FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
    SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
    PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
    TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
    SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
    c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
    +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
    ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
    b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
    U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
    MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
    5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
    9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
    WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
    he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
    Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
    -----END CERTIFICATE-----
- path: /etc/nginx/sites-enabled/fwpoctimw.uksouth.cloudapp.azure.com
  content: |
    server {

        server_name fwpoctimw.uksouth.cloudapp.azure.com;

        root /var/www/fwpoctimw.uksouth.cloudapp.azure.com;
        index index.html;

        location / {
          try_files $uri $uri/ =404;
        }

        listen [::]:443 ssl ipv6only=on; # managed by Certbot
        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/fwpoctimw.uksouth.cloudapp.azure.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/fwpoctimw.uksouth.cloudapp.azure.com/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    }
    server {
        if ($host = fwpoctimw.uksouth.cloudapp.azure.com) {
            return 301 https://$host$request_uri;
        } # managed by Certbot


        listen 80;
        listen [::]:80;

        server_name fwpoctimw.uksouth.cloudapp.azure.com;
        return 404; # managed by Certbot
    }
runcmd:
  - systemctl restart nginx