name: firewall-stop

on:
  # enable manual trigger
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'Resource group name'
        default: ''
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.TF_SP_CREDS}}
        enable-AzPSSession: true 

    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $azfw = Get-AzFirewall -Name "fw-poc" -ResourceGroupName ${{ github.event.inputs.resourceGroup }}
          $azfw.Deallocate()
          Set-AzFirewall -AzureFirewall $azfw
        azPSVersion: 'latest'